//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace Laigio.SGCJLPSPG_Weber
{
	/// <summary>
	/// DomainRelationship ExampleModelHasElements
	/// Embedding relationship between the Model and Elements
	/// </summary>
	[DslDesign::DisplayNameResource("Laigio.SGCJLPSPG_Weber.ExampleModelHasElements.DisplayName", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Laigio.SGCJLPSPG_Weber.ExampleModelHasElements.Description", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("4b6dc5d9-768a-4fb7-9790-0e0dd7918018")]
	public partial class ExampleModelHasElements : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleModelHasElements domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x4b6dc5d9, 0x768a, 0x4fb7, 0x97, 0x90, 0x0e, 0x0d, 0xd7, 0x91, 0x80, 0x18);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleModelHasElements link in the same Partition as the given ExampleModel
		/// </summary>
		/// <param name="source">ExampleModel to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleModelHasElements(ExampleModel source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleModelHasElements.ExampleModelDomainRoleId, source), new DslModeling::RoleAssignment(ExampleModelHasElements.ElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ExampleModel domain role code
		
		/// <summary>
		/// ExampleModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid ExampleModelDomainRoleId = new global::System.Guid(0xaf8b22cd, 0x0a00, 0x4c89, 0xa6, 0x08, 0x45, 0xfa, 0xb6, 0x8e, 0x5f, 0x89);
		
		/// <summary>
		/// DomainRole ExampleModel
		/// </summary>
		[DslDesign::DisplayNameResource("Laigio.SGCJLPSPG_Weber.ExampleModelHasElements/ExampleModel.DisplayName", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Laigio.SGCJLPSPG_Weber.ExampleModelHasElements/ExampleModel.Description", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Elements", PropertyDisplayNameKey="Laigio.SGCJLPSPG_Weber.ExampleModelHasElements/ExampleModel.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("af8b22cd-0a00-4c89-a608-45fab68e5f89")]
		public virtual ExampleModel ExampleModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, ExampleModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ExampleModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ExampleModel of a ExampleElement
		/// <summary>
		/// Gets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static ExampleModel GetExampleModel(ExampleElement element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ElementDomainRoleId) as ExampleModel;
		}
		
		/// <summary>
		/// Sets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetExampleModel(ExampleElement element, ExampleModel newExampleModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ElementDomainRoleId, newExampleModel);
		}
		#endregion
		#region Element domain role code
		
		/// <summary>
		/// Element domain role Id.
		/// </summary>
		public static readonly global::System.Guid ElementDomainRoleId = new global::System.Guid(0x42d0480d, 0xf730, 0x49d1, 0x97, 0x69, 0x28, 0x77, 0xd5, 0x09, 0x3b, 0xb5);
		
		/// <summary>
		/// DomainRole Element
		/// </summary>
		[DslDesign::DisplayNameResource("Laigio.SGCJLPSPG_Weber.ExampleModelHasElements/Element.DisplayName", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Laigio.SGCJLPSPG_Weber.ExampleModelHasElements/Element.Description", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ExampleModel", PropertyDisplayNameKey="Laigio.SGCJLPSPG_Weber.ExampleModelHasElements/Element.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("42d0480d-f730-49d1-9769-2877d5093bb5")]
		public virtual ExampleElement Element
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, ElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Elements of a ExampleModel
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetElements(ExampleModel element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, ExampleModelDomainRoleId);
		}
		#endregion
		#region ExampleModel link accessor
		/// <summary>
		/// Get the list of ExampleModelHasElements links to a ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements> GetLinksToElements ( global::Laigio.SGCJLPSPG_Weber.ExampleModel exampleModelInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements>(exampleModelInstance, global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements.ExampleModelDomainRoleId);
		}
		#endregion
		#region Element link accessor
		/// <summary>
		/// Get the ExampleModelHasElements link to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements GetLinkToExampleModel (global::Laigio.SGCJLPSPG_Weber.ExampleElement elementInstance)
		{
			global::System.Collections.Generic.IList<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements>(elementInstance, global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements.ElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Element not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ExampleModelHasElements instance accessors
		
		/// <summary>
		/// Get any ExampleModelHasElements links between a given ExampleModel and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements> GetLinks( global::Laigio.SGCJLPSPG_Weber.ExampleModel source, global::Laigio.SGCJLPSPG_Weber.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements> outLinks = new global::System.Collections.Generic.List<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements>();
			global::System.Collections.Generic.IList<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements>(source, global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleModelHasElements link between a given ExampleModeland a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements GetLink( global::Laigio.SGCJLPSPG_Weber.ExampleModel source, global::Laigio.SGCJLPSPG_Weber.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements>(source, global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::Laigio.SGCJLPSPG_Weber.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Laigio.SGCJLPSPG_Weber
{
	/// <summary>
	/// DomainRelationship ExampleElementReferencesTargets
	/// Reference relationship between Elements.
	/// </summary>
	[DslDesign::DisplayNameResource("Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets.DisplayName", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets.Description", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("83024976-6c6e-4fc7-acd0-3312eea8e408")]
	public partial class ExampleElementReferencesTargets : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleElementReferencesTargets domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x83024976, 0x6c6e, 0x4fc7, 0xac, 0xd0, 0x33, 0x12, 0xee, 0xa8, 0xe4, 0x08);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleElementReferencesTargets link in the same Partition as the given ExampleElement
		/// </summary>
		/// <param name="source">ExampleElement to use as the source of the relationship.</param>
		/// <param name="target">ExampleElement to use as the target of the relationship.</param>
		public ExampleElementReferencesTargets(ExampleElement source, ExampleElement target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleElementReferencesTargets.SourceDomainRoleId, source), new DslModeling::RoleAssignment(ExampleElementReferencesTargets.TargetDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleElementReferencesTargets(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleElementReferencesTargets(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleElementReferencesTargets(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleElementReferencesTargets(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Source domain role code
		
		/// <summary>
		/// Source domain role Id.
		/// </summary>
		public static readonly global::System.Guid SourceDomainRoleId = new global::System.Guid(0x184e4690, 0x9830, 0x410e, 0xac, 0x3f, 0x04, 0xfe, 0xb6, 0x4d, 0xb0, 0x71);
		
		/// <summary>
		/// DomainRole Source
		/// Description for Laigio.SGCJLPSPG_Weber.ExampleRelationship.Target
		/// </summary>
		[DslDesign::DisplayNameResource("Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets/Source.DisplayName", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets/Source.Description", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Targets", PropertyDisplayNameKey="Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets/Source.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("184e4690-9830-410e-ac3f-04feb64db071")]
		public virtual ExampleElement Source
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, SourceDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, SourceDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Sources of a ExampleElement
		/// <summary>
		/// Gets a list of Sources.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetSources(ExampleElement element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, TargetDomainRoleId);
		}
		#endregion
		#region Target domain role code
		
		/// <summary>
		/// Target domain role Id.
		/// </summary>
		public static readonly global::System.Guid TargetDomainRoleId = new global::System.Guid(0x63cadbe9, 0x61e9, 0x4201, 0xbd, 0x8e, 0x5b, 0x25, 0xe5, 0xc6, 0x76, 0x13);
		
		/// <summary>
		/// DomainRole Target
		/// Description for Laigio.SGCJLPSPG_Weber.ExampleRelationship.Source
		/// </summary>
		[DslDesign::DisplayNameResource("Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets/Target.DisplayName", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets/Target.Description", typeof(global::Laigio.SGCJLPSPG_Weber.SGCJLPSPG_WeberDomainModel), "Laigio.SGCJLPSPG_Weber.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Sources", PropertyDisplayNameKey="Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets/Target.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("63cadbe9-61e9-4201-bd8e-5b25e5c67613")]
		public virtual ExampleElement Target
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleElement)DslModeling::DomainRoleInfo.GetRolePlayer(this, TargetDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TargetDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Targets of a ExampleElement
		/// <summary>
		/// Gets a list of Targets.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<ExampleElement> GetTargets(ExampleElement element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<ExampleElement>, ExampleElement>(element, SourceDomainRoleId);
		}
		#endregion
		#region Source link accessor
		/// <summary>
		/// Get the list of ExampleElementReferencesTargets links to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets> GetLinksToTargets ( global::Laigio.SGCJLPSPG_Weber.ExampleElement sourceInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets>(sourceInstance, global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets.SourceDomainRoleId);
		}
		#endregion
		#region Target link accessor
		/// <summary>
		/// Get the list of ExampleElementReferencesTargets links to a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets> GetLinksToSources ( global::Laigio.SGCJLPSPG_Weber.ExampleElement targetInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets>(targetInstance, global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets.TargetDomainRoleId);
		}
		#endregion
		#region ExampleElementReferencesTargets instance accessors
		
		/// <summary>
		/// Get any ExampleElementReferencesTargets links between a given ExampleElement and a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets> GetLinks( global::Laigio.SGCJLPSPG_Weber.ExampleElement source, global::Laigio.SGCJLPSPG_Weber.ExampleElement target )
		{
			global::System.Collections.Generic.List<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets> outLinks = new global::System.Collections.Generic.List<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets>();
			global::System.Collections.Generic.IList<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets>(source, global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets.SourceDomainRoleId);
			foreach ( global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleElementReferencesTargets link between a given ExampleElementand a ExampleElement.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets GetLink( global::Laigio.SGCJLPSPG_Weber.ExampleElement source, global::Laigio.SGCJLPSPG_Weber.ExampleElement target )
		{
			global::System.Collections.Generic.IList<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets>(source, global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets.SourceDomainRoleId);
			foreach ( global::Laigio.SGCJLPSPG_Weber.ExampleElementReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
