//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laigio.SGCJLPSPG_Weber
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "SGCJLPSPG_DSLWeber";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"SGCJLPSPG_Weber";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Laigio";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID SGCJLPSPG_WeberDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SGCJLPSPG_WeberCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID SGCJLPSPG_WeberExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SGCJLPSPG_WeberCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewSGCJLPSPG_WeberExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SGCJLPSPG_WeberCommandSetId), 0x0001);
	
		// Package identifier
		public const string SGCJLPSPG_WeberPackageId = "132debac-0e62-4baa-8583-1d11e894368a";
		
		// Editor factory identifier
		public const string SGCJLPSPG_WeberEditorFactoryId = "6db1156a-f712-446b-b07e-8a86ffb3f851";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string SGCJLPSPG_WeberModelExplorerToolWindowId = "03454d1a-e7ca-45d2-8fec-9e5df12c7013";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Laigio.SGCJLPSPG_Weber
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string SGCJLPSPG_WeberCommandSetId = "adec5ce2-9fa4-4c52-917d-ddff69ff6792";
	}
}